### ISSUE TITLE
Unable to cast uint from bool expression

### ISSUE THREAD

**Issue by emoon** [GameTechDev/SPIRV-Cross#2]
When having an expression like this

```
uint t = dot(v, v) > 0;
```

ISPC will complain about `Unable to find any matching overload for call to function "int_cast"`

This can be fixed by adding this to the generated ispc header file

```
static SPIRV_INLINE varying int int_cast(varying bool& a) { return (varying int) a; }
```

**Comment by jonckennedy** [comment]
good catch. I shall add bools to the autogen cast functions.

Thanks
