### ISSUE TITLE
Accessing xyz in a float4 isn't supported

### ISSUE THREAD

**Issue by emoon** [GameTechDev/SPIRV-Cross#3]
In HLSL it's supported to write like this

```
float4 t = float4(v.xyz, 1.0f);
```

This doesn't currently work. It's possible to do a workaround like this:

```
float4 t = v;
t.w = 1.0f;
```

**Comment by jonckennedy** [comment]
It should do. spirv-cross should expand this to 
`float4 t = float4(float3(v.x, v.y, v.z), 1.0f);`

I'll look into it.

**Comment by HansKristian-Work** [comment]
This is likely the swizzle collapse step in OpCompositeConstruct (or OpVectorShuffle).

**Comment by jonckennedy** [comment]
It was in build_composite_combiner when `can_apply_swizzle_opt` is true. Fixed locally via a new backend compiler option `supports_native_swizzle`.
