### ISSUE TITLE
Local atomic issues

### ISSUE THREAD

**Issue by emoon** [GameTechDev/SPIRV-Cross#5]
I'm trying to get local atomics going. The main issue is that there is no `groupshared` support yet.

This HLSL code works just as expected

```
RWStructuredBuffer<uint> g_globalMeshCounter : register(u1);

[numthreads(1, 1, 1)]
void csEntry(
	uint groupIdx : SV_GroupID,
	uint localIdx : SV_GroupThreadID)
{
	uint offset;
	InterlockedAdd(g_globalMeshCounter[0], 1, offset);
}
```

And the generated ISPC code ends up being

```
static SPIRV_INLINE void temp_ispc_main( uniform struct type_RWStructuredBuffer_uint& g_globalMeshCounter, varying int3 gl_LocalInvocationID, uniform int3 gl_WorkGroupID)
{
    varying int _20 = atomic_add(&g_globalMeshCounter._m0[0u], 1u);
}
```

So while this is fine if it's a global counter but there are cases where you don't want to hit main memory with your atomics but instead keeping them local to the workgroup. The current way I have been dealing with this is to write something like this

```
#undef groupshared
#define groupshared static

groupshared uint g_globalMeshCounter;

[numthreads(1, 1, 1)]
void csEntry(
	uint groupIdx : SV_GroupID,
	uint localIdx : SV_GroupThreadID)
{
	uint offset;
	InterlockedAdd(g_globalMeshCounter, 1, offset);
}
```

Comping this with DXC makes it sad. 

```
fatal error: generated SPIR-V is invalid: AtomicIAdd: expected Pointer Storage Class to be Uniform, Workgroup, CrossWorkgroup, Generic, AtomicCounter, Image or StorageBuffer
  %14 = OpAtomicIAdd %uint %g_globalMeshCounter %uint_1 %uint_0 %uint_1
```

As the storage format isn't correct here. The current workaround for this would be to always have input buffers for the ISPC case but it makes the code a bit annoying to deal with.

**Comment by jonckennedy** [comment]
OK, groupshared is not implemented. If groupshared just mapped to a global scope uniform static variable, would that work for you? 

I would then add a version of the atomics that took that as an argument.

You could experiment by changing the `groupshared uint g_globalMeshCounter` to be `groupshared uint g_globalMeshCounter[1]`. That would force it to be a pointer type. You may also need to ensure the underlying ISPC variable is a uniform...

**Comment by emoon** [comment]
I don't think mapping it to a global static would work as it wouldn't be thread safe right?. I will give your suggestion with `g_gloablMeshCounter[1]` a try.

**Comment by HansKristian-Work** [comment]
Would it be possible to implement groupshared by passing down a pointer to workgroup state to the kernel function? I.e the "run workgroup" entry point would allocate the state on stack, and pass that down.

**Comment by emoon** [comment]
Having it on the stack and being passed down will likely work fine.

**Comment by jonckennedy** [comment]
Yes, that would make sense. Good suggestion.
