### ISSUE TITLE
GroupMemoryBarrierWithGroupSync generates undeclared symbol

### ISSUE THREAD

**Issue by emoon** [GameTechDev/SPIRV-Cross#6]
Given the following code

```
[numthreads(1, 1, 1)]
void csEntry(
	uint groupIdx : SV_GroupID,
	uint localIdx : SV_GroupThreadID)
{
	GroupMemoryBarrierWithGroupSync();
}
```

Generates this ISPC

```
static SPIRV_INLINE void temp_ispc_main(varying int3 gl_LocalInvocationID, uniform int3 gl_WorkGroupID)
{
    memoryBarrierShared();
    barrier();
}
```

And the compiler will complain about

```
file.ispc:25:5: Error: Undeclared symbol "memoryBarrierShared".
    memoryBarrierShared();
    ^^^^^^^^^^^^^^^^^^^

file.ispc:26:5: Error: Undeclared symbol "barrier".
    barrier();
    ^^^^^^^
```

**Comment by jonckennedy** [comment]
Thanks for reporting the issue.

Shared memory, barriers and syncs are currently not supported.

To properly implement a sync, each kernel would need splitting into 2 at the sync point with all state captured, stored and passed to the continuation kernel. This has a high degree of complexity so has been avoided until now.

The recommendation is to make the work group size equal to the gang size, and then no syncs are required, assuming single threaded operation. Alternatively, you could do this yourself by reducing the size of the work group by N, but getting each work item to process N things and controlling your own internal loops etc.

**Comment by emoon** [comment]
Alright. In my case I can likely just `ifdef` it to nothing as I don't do any syncing in that way that requires splitting.

**Comment by jonckennedy** [comment]
I could maybe add it as an option to silently ignore unknown options, but I prefer that the developer realises that it isn't supported rather than silently ignoring...?

**Comment by HansKristian-Work** [comment]
Another alternative is to throw error on unimplementable things, then suggest user to using a flag to ignore synchronization explicitly. Silently ignoring sounds like it would enable a developer to think barriers should work, but it actually doesn't.

Does the ISPC backend know the SIMD width? In that case, it could silently allow sync barriers if work group size < N because they are noops.

**Comment by jonckennedy** [comment]
Good idea.

The ISPC backend doesn't know the SIMD width as that is an ISPC-compiler compile time argument.
